version: "3"
services:
  silverbullet:
    image: zefhemel/silverbullet
    restart: unless-stopped
    env_file: stack.env
    volumes:
      - space:/space
    ports:
      - 3008:3000
volumes:
  space:
